baseURL = "https://shanedavis.net/"
languageCode = "en-us"
title = "shanedavis.net"
theme = "m10c"
googleAnalytics = "UA-75233516-1"

[params]
  author = "Shane Davis"
  description = "A short description goes here."
    [[params.social]]
        name = "github"
        url = "https://github.com/sdavis3"
    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/shane_b_davis"
    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/shanebdavis/"

[params.style]
    darkestColor = "#d35050"
    darkColor = "#212121"
    lightColor = "#f5e3e0"
    lightestColor = "#f5f5f5"
    primaryColor = "#fff"